### ISSUE TITLE
Issue with auto.native

### ISSUE THREAD

**Issue by threonorm** [leanprover-community/lean-auto#37]
Hi,

I was trying to play around with the different backend solver, and especially the native on. From [here](https://github.com/leanprover-community/lean-auto/blob/main/Test/Test_Regression.lean) I tried to look up how to use the native solver, and after investigation using the same command for emulateNative, it seems auto is not sound (or maybe I am misunderstanding how to use it?):

```lean
import Auto.Tactic

set_option auto.native true
attribute [rebind Auto.Native.solverFunc] Auto.Solver.Native.emulateNative

example : False := by auto 
-- It seems to say that it has found a proof in 1ms (but it used sorry to admit the proof)
```
(Tested with commit 60e546ca7a9d40d508e58847a9d0630406835178, Lean v4.11)

**Comment by PratherConid** [comment]
Sorry for the confusion. ``emulateNative`` always uses ``sorry`` to close the goal. I've added a paragraph in ``readme`` to explain how to use the native solver ``duper``
