### ISSUE TITLE
Feature request: configuration option to allow the user to change solver timeouts

### ISSUE THREAD

**Issue by shigoel** [leanprover-community/lean-auto#8]
It looks like the timeout is hard-coded right now?
https://github.com/leanprover-community/lean-auto/blob/main/Auto/Solver/SMT.lean#L70

**Comment by PratherConid** [comment]
I've added `auto.smt.timeout`.

**Comment by shigoel** [comment]
Thank you so much, @PratherConid, for your promptness, especially since you're on a break till early Jan.! Appreciate it.
